### ISSUE TITLE
OAuth2 credentials have expired and can't be refreshed

### ISSUE THREAD

**Issue by luoei** [rinukkusu/spotify-dart#116]
```
flutter: 
#0      Client.send (package:oauth2/src/client.dart:109:36)
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
#2      BaseClient.get (package:http/src/base_client.dart:27:7)
#3      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:152:31)
<asynchronous suspension>
#4      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:185:29)
<asynchronous suspension>
#5      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:151:12)
```
version: 0.7.0
How should this be fixed?

**Comment by rinukkusu** [comment]
I'd suggest getting a new OAuth access token 🤔
