### ISSUE TITLE
Playlist info, tracks and artists

### ISSUE THREAD

**Issue by addreeh** [rinukkusu/spotify-dart#179]
Is there anyway to get each track from the playlist one by one? And the artist and the name of the track?
I have this code:

```dart
import 'package:flutter/material.dart';
import 'package:spotify/spotify.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const SecondPage(),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Page'),
      ),
      body: Column(
        children: [
          ElevatedButton(
              onPressed: () async {
                // OBTENER CANALES DEL USUARIO
                print("DENTRO");
                final credentials = SpotifyApiCredentials(
                    "",
                    "");
                var spotify = SpotifyApi(credentials);
                print("PLAYLIST");
                var playlist =
                    await spotify.playlists.get("0UNaot0tAdf4Oqa8L1hK88");

                var tracks = spotify.playlists
                    .getTracksByPlaylistId("0UNaot0tAdf4Oqa8L1hK88")
                    .all;

                print(tracks);

                for (var i = 0; i < (playlist.tracks?.total ?? 0); i++) {}

// ...

                print("TOTAL CANCIONES ${playlist.tracks?.total ?? 0}");

                print(tracks);

                print(playlist.name);
                print(playlist.description);
                print(playlist.owner?.displayName);
                print(playlist.tracks?.itemsNative);
                print("TOTAL CANCIONES ${playlist.tracks?.total}");
                print("FOLLOWERS ${playlist.followers?.total}");
              },
              child: Text("MANOLO")),
          ElevatedButton(
            onPressed: () async {
              print("DENTRO");
              final credentials = SpotifyApiCredentials(
                  "",
                  "");
              var spotify = SpotifyApi(credentials);
              print("PLAYLIST");

              var tracks = await spotify.playlists
                  .getTracksByPlaylistId("0UNaot0tAdf4Oqa8L1hK88")
                  .all(100);

              var cont = 0;
              // Imprimir información de cada pista
              for (var track in tracks) {
                try {
                  print(cont);
                  print(track.trackNumber);
                  print("ALBUM ${track.album?.name}");

                  print(track.artists);

                  print(track.durationMs);
                  print('Canción: ${track.name}');
                  cont++;
                } catch (Exception) {
                  print("CHEEEEEEEEEE");
                }
              }
            },
            child: Text("PEDRO"),
          ),
        ],
      ),
    );
  }
}
```

and its returns me some tracks, and some info:
```
I/flutter (28113): Canción: AYER
I/flutter (28113): 478
I/flutter (28113): 15
I/flutter (28113): ALBUM THE KINGTAPE
I/flutter (28113): [Instance of 'Artist', Instance of 'Artist']
I/flutter (28113): 221534
I/flutter (28113): Canción: Dos Días
I/flutter (28113): 479
I/flutter (28113): 1
I/flutter (28113): ALBUM Entre Nosotros (Mashup)
I/flutter (28113): [Instance of 'Artist']
I/flutter (28113): 345783
I/flutter (28113): Canción: Entre Nosotros - Mashup
E/flutter (28113): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'
E/flutter (28113): #0      Playlists.getTracksByPlaylistId.<anonymous closure> (package:spotify/src/endpoints/playlists.dart:41:38)
E/flutter (28113): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
E/flutter (28113): #2      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
E/flutter (28113): #3      ExpandIterator.moveNext (dart:_internal/iterable.dart:477:32)
E/flutter (28113): #4      SecondPage.build.<anonymous closure> (package:trackerfy/mierda.dart:79:33)
E/flutter (28113): <asynchronous suspension>

```

But it dont show all the tracks, the playlist has 700 tracks and it stopped at 479, also i dont know if is posible to get the artists and the album

**Comment by hayribakici** [comment]
@addreeh Please edit your code in your first post with the `Edit` function. 

<img src="https://github.com/rinukkusu/spotify-dart/assets/3295340/9d72c3b6-3085-4775-9b5d-b677b23f4e37" height="100px" />


Regarding your error, it seems that there is a json weirdness going on. Looks like that this library is expecting a json object, which does not exist. If you are able to paste your json, we could see where the error is.

**Comment by rinukkusu** [comment]
Can you pinpoint on which line you get the error? It's a little hard to visually debug your code just with the log clues.

**Comment by hayribakici** [comment]
You can retrieve the `json` by pasting your id [on this spotify website](https://developer.spotify.com/documentation/web-api/reference/get-playlists-tracks).

**Comment by hayribakici** [comment]
@addreeh you would need to play around with the `limit` and `offset` values. So for example, set `offset` and `limit` to `300` and look for the track "Know No Better (feat. Travis Scott & Quavo) [Bad Bunny Remix]", since the error happens after this.

**Comment by hayribakici** [comment]
It seems that the playlist json does not contain any tracks after a certain offset. But we need proof for this.

@addreeh I suggest to play around with the `limit` and `offset` values. So for example, set `offset` to `300` and beyond and and look for the track "Know No Better (feat. Travis Scott & Quavo) [Bad Bunny Remix]", since the error happens after this.

**Comment by hayribakici** [comment]
Okay, this is a bug. We only support `tracks` so far. Spotify provides a filter in which we can restrict the return types. Thank you for pointing this out! :)
