### ISSUE TITLE
Bug: `album.tracks` throwing exception "type 'double' is not a subtype of type 'int?' in type cast"

### ISSUE THREAD

**Issue by KRTirtho** [rinukkusu/spotify-dart#207]
Now, `album.tracks` endpoint's `Paging` is also infected. It says it's the `limit`, but I doubt it's happening for every `int` type fields. I doubt it'll start to happen for other fields as well

```
#0      _$PagingFromJson (package:spotify/src/models/_models.g.dart:523:27)
#1      new Paging.fromJson (package:spotify/src/models/paging.dart:44:57)
#2      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:240:20)
<asynchronous suspension>
#3      AlbumQueries.tracksOfJob.<anonymous closure> (package:spotube/services/queries/album.dart:45:11)
<asynchronous suspension>
#4      _AsyncCompleter.complete (dart:async/future_impl.dart:41:3)
<asynchronous suspension>
#5      Retryer.retryOperation (package:fl_query/src/core/mixins/retryer.dart:17:7)
<asynchronous suspension>
#6      CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425:16)
<asynchronous suspension>
```

**Comment by rinukkusu** [comment]
Thanks for chiming in - your fix has been published with `0.13.3`!

**Comment by KRTirtho** [comment]
Awesome. Thanks for being so quick 😄

**Comment by KRTirtho** [comment]
It works fine. I tested the changes with my app
